<?

// $Id$

header('Content-type: text/html; charset=utf-8');
echo("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
/*echo("<?xml-stylesheet type=\"text/xsl\" " .
     "href=\"" . SITE_URL . "/mathml/mathml.xsl\"?>\n");*/

?>
<!DOCTYPE html PUBLIC
    "-//W3C//DTD XHTML 1.1 plus MathML 2.0//EN"
    "http://www.w3.org/Math/DTD/mathml2/xhtml-math11-f.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru">
<head>
<title><?= $title ?></title>
</head>
<body>

<div id="titlebar">
Title Bar
</div>

<div id="content">

<?php

if(is_a($content, 'Template')) { 
    $content->fillAndPrint(); 
} else {
    echo($content);
}

?>

</div>


<div id="footbar">
Foot Bar
</div>

</body>
</html>
