<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Creating new image</title>
<script type="text/javascript">
function updateNames() {
    var input = document.getElementById('name');
    var spanBig = document.getElementById('nameBig');
    var spanSmall = document.getElementById('nameSmall');
    spanBig.normalize();
    spanBig.removeChild(spanBig.firstChild);
    spanBig.appendChild(document.createTextNode(input.value + '.jpg'));
    spanSmall.normalize();
    spanSmall.removeChild(spanSmall.firstChild);
    spanSmall.appendChild(document.createTextNode(input.value + 's.jpg'));
}
</script>
</head>
<body>

<h1>Creating new image</h1>

<form action="<?= $action ?>" method="post">
<fieldset>
<legend>Specify image details</legend>
<input name="typeName" type="hidden" value="<?= $typeName ?>" />

<table>

<tr>
<td><label for="name">Image name</label></td>
<td>
<input name="name" id="name" type="text" size="20" onkeyup="updateNames()" />
</td>
</tr>

<tr>
<td colspan="2">
<ul>
<li><?= $dir ?>/<span id="nameBig">???</span> &mdash; big</li>
<li><?= $dir ?>/<span id="nameSmall">???</span> &mdash; small</li>
</ul>
</td>
</tr>

<tr>
<td><label for="title">Image title</label></td>
<td>
<input name="title" id="title" type="text" size="75" />
</td>
</tr>

<tr>
<td><label for="authors">Image authors</label></td>
<td>
<input name="authors" id="authors" type="text" size="75" />
</td>
</tr>

<tr>
<td><label for="isVisible">Is visible?</label></td>
<td>
<input name="isVisible" id="isVisible" type="checkbox" value="1" checked="checked" />
</td>
</tr>

</table>
</fieldset>
<button type="submit">Submit</button>
<button type="reset">Reset</button>
</form>

</body>
</html>
