<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?= $treeNode->getTitle() ?> &mdash; My Site</title>
</head>
<body>

<h1><?= $treeNode->getTitle() ?></h1>

<ul>
<?

foreach($childPreviews as $preview) { 
    echo('<li>' . $preview . '</li>');
}

?>
</ul>

<?
if ($childIndex > 0) {

?>

<a href="?f=<?php echo(max(0, $childIndex - 10)); ?>">Prev page</a>

<?php

}

if ($childIndex + 10 < $childCount) {

?>

<a href="?f=<?php echo($childIndex + 10); ?>">Next page</a>

<?php

}

?>

</body>
</html>
