<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Create article</title>
</head>
<body>

<form action="<?= $action ?>" method="post">
<fieldset>
<legend>Create article</legend>
<input name="typeName" type="hidden" value="<?= $typeName ?>" />

<table>

<tr>
<td><label for="name">Article name</label></td>
<td>
<input name="name" id="name" type="text" size="20" />
</td>
</tr>

<tr>
<td><label for="hasOwnDir">Has own subdirectory?</label></td>
<td>
<input name="hasOwnDir" id="hasOwnDir" type="checkbox" />
</td>
</tr>

<tr>
<td><label for="title">Article title</label></td>
<td>
<input name="title" id="title" type="text" size="75" />
</td>
</tr>

<tr>
<td><label for="listChildren">List children?</label></td>
<td>
<input name="listChildren" id="listChildren" type="checkbox" />
</td>
</tr>

<tr>
<td><label for="isVisible">Is visible?</label></td>
<td>
<input name="isVisible" id="isVisible" type="checkbox" checked="checked" />
</td>
</tr>

</table>
</fieldset>
<button type="submit">Submit</button>
<button type="reset">Reset</button>
</form>

</body>
</html>
