<?

// $Id$

assert('is_string($content)');
assert('!isset($children) || is_array($children)');
assert('Util::isArrayOf($authors, \'User\')');

?>

<?= $content ?>

<?
    if (isset($children) && count($children) > 0) {
        echo("<ul>\n");
        foreach ($children as $child) {
            echo("<li>" . $child . "</li>\n");
        }
        echo("</ul>\n");
    }
?>

<? if (count($authors) > 0) { ?><p class="singature"><? $this->printAuthors($authors) ?></p><? } ?>
