<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?= $treeNode->getTitle() ?> &mdash; My Site</title>
</head>
<body>

<h1><?= $treeNode->getTitle() ?></h1>

<?= $content ?>

<?
    if (isset($children) && count($children) > 0) {
        echo("<ul>\n");
        foreach ($children as $child) {
            echo("<li>" . $child . "</li>\n");
        }
        echo("</ul>\n");
    }
?>

<? if (count($authors) > 0) { ?><p class="singature"><? $this->printAuthors($authors) ?></p><? } ?>

</body>
</html>
