<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<title>Redirecting</title>
</head>
<body>

<h1>Redirecting</h1>

<p>
    You are being redirected to another page:
    <code><a href="<?= $url ?>"><?= $url ?></a></code>.<br />
    Please use the link above if it does not happen
    automatically.
</p>

</body>
</html>
