<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Creating new gallery</title>
</head>
<body>

<h1>Creating new gallery</h1>

<form action="<?= $action ?>" method="post">
<fieldset>
<legend>Specify image details</legend>
<input name="typeName" type="hidden" value="<?= $typeName ?>" />

<table>

<tr>
<td><label for="name">Gallery name</label></td>
<td>
<input name="name" id="name" type="text" size="20" />
</td>
</tr>

<tr>
<td colspan="2">
    Images will be stored in <code><?= $basedir ?>/<i>name</i></code>.<br />
    <code>icon.jpg</code> will be the icon for this gallery.
</td>
</tr>

<tr>
<td><label for="title">Gallery title</label></td>
<td>
<input name="title" id="title" type="text" size="75" />
</td>
</tr>

<tr>
<td><label for="isVisible">Is visible?</label></td>
<td>
<input name="isVisible" id="isVisible" type="checkbox" checked="checked" />
</td>
</tr>

</table>
</fieldset>
<button type="submit">Submit</button>
<button type="reset">Reset</button>
</form>

</body>
</html>
