<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Editing image</title>
</head>
<body onload="updateNames()">

<h1>Editing image</h1>

<form action="<?= $action ?>" method="post">
<fieldset>
<legend>Specify image details</legend>
<table>

<tr>
<td><label for="name">Image name</label></td>
<td>
<input name="name" id="name" type="text" size="20" value="<?= $name ?>" />
</td>
</tr>

<tr>
<td colspan="2">
<ul>
<li><code><?= $dir ?>/<i>name</i>.jpg</code> &mdash; big</li>
<li><code><?= $dir ?>/<i>name</i>s.jpg</code> &mdash; small</li>
</ul>
</td>
</tr>

<tr>
<td><label for="title">Image title</label></td>
<td>
<input name="title" id="title" type="text" value="<?= $title ?>" size="75" />
</td>
</tr>

<tr>
<td><label for="authors">Image authors</label></td>
<td>
<input name="authors" id="authors" type="text" value="<?= $authors ?>" size="75" />
</td>
</tr>

<tr>
<td><label for="isVisible">Is visible?</label></td>
<td>
<input name="isVisible" id="isVisible" type="checkbox" value="1"<?= $isVisible? ' checked="checked"' : '' ?> />
</td>
</tr>

</table>
</fieldset>
<button type="submit">Submit</button>
<button type="reset">Reset</button>
</form>

</body>
</html>
