<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Login form</title>
</head>
<body>

<h1>Login form</h1>

<? if (isset($message)): ?>
<p>
<?= $message ?>
</p>
<? endif ?>

<form action="<?= $action ?>" method="post">
<legend>Please enter your password</legend>
<p>
<input type="password" name="password" />
<button type="submit">Login</button>
</p>
</form>

</body>
</html>
