<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<title>Edit node</title>
</head>
<body>

<form name="edit" id="edit" action="<?= $action ?>" method="post">
<fieldset>
<legend>Node Properties</legend>
<table>
<?php
    foreach ($properties as $property) {
?>
<tr>
<td><label for="<?= $property->getName() ?>"><?= $property->getTitle() ?></label></td>
<td>
<?= $property->getControl() ?>
</td>
</tr>
<?php
    }
?>
</table>
</fieldset>
<button type="submit">Submit</button>
<button type="reset">Reset</button>
</form>

</body>
</html>
