<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Edit list properties</title>
</head>
<body>

<form action="<?= $action ?>" method="post">
<fieldset>
<legend>Edit list properties</legend>
<table>

<tr>
<td><label for="title">News title</label></td>
<td>
<input name="title" id="title" type="text" value="<?= $title ?>" size="75" />
</td>
</tr>

<tr>
<td><label for="isVisible">Is visible?</label></td>
<td>
<input name="isVisible" id="isVisible" type="checkbox"<? if ($isVisible) echo(" checked=\"checked\""); ?> />
</td>
</tr>

<tr>
<td><label for="order">Sort order</label></td>
<td>
<select name="order" id="order">
<option value="title ASC">By title</option>
</select>
</td>
</tr>

</table>
</fieldset>
<button type="submit">Submit</button>
<button type="reset">Reset</button>
</form>

</body>
</html>
